<?php
// This script and data application was generated by AppGini, https://bigprof.com/appgini
// Download AppGini for free from https://bigprof.com/appgini/download/

	include_once(__DIR__ . '/lib.php');
	@include_once(__DIR__ . '/hooks/circles.php');
	include_once(__DIR__ . '/circles_dml.php');

	// mm: can the current member access this page?
	$perm = getTablePermissions('circles');
	if(!$perm['access']) {
		echo error_message($Translation['tableAccessDenied']);
		exit;
	}

	$x = new DataList;
	$x->TableName = 'circles';

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = [
		"`circles`.`id`" => "id",
		"`circles`.`owner_id`" => "owner_id",
		"`circles`.`name`" => "name",
		"`circles`.`created_at`" => "created_at",
	];
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = [
		1 => '`circles`.`id`',
		2 => '`circles`.`owner_id`',
		3 => 3,
		4 => '`circles`.`created_at`',
	];

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = [
		"`circles`.`id`" => "id",
		"`circles`.`owner_id`" => "owner_id",
		"`circles`.`name`" => "name",
		"`circles`.`created_at`" => "created_at",
	];
	// Fields that can be filtered
	$x->QueryFieldsFilters = [
		"`circles`.`id`" => "Id",
		"`circles`.`owner_id`" => "Owner id",
		"`circles`.`name`" => "Name",
		"`circles`.`created_at`" => "Created at",
	];

	// Fields that can be quick searched
	$x->QueryFieldsQS = [
		"`circles`.`id`" => "id",
		"`circles`.`owner_id`" => "owner_id",
		"`circles`.`name`" => "name",
		"`circles`.`created_at`" => "created_at",
	];

	// Lookup fields that can be used as filterers
	$x->filterers = [];

	$x->QueryFrom = "`circles` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm['view'] == 0 ? 1 : 0);
	$x->AllowDelete = $perm['delete'];
	$x->AllowMassDelete = (getLoggedAdmin() !== false);
	$x->AllowInsert = $perm['insert'];
	$x->AllowUpdate = $perm['edit'];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = (getLoggedAdmin() !== false);
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = 1;
	$x->AllowAdminShowSQL = showSQL();
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation['quick search'];
	$x->ScriptFileName = 'circles_view.php';
	$x->TableTitle = 'Circles';
	$x->TableIcon = 'table.gif';
	$x->PrimaryKey = '`circles`.`id`';

	$x->ColWidth = [150, 150, 150, 150, ];
	$x->ColCaption = ['Id', 'Owner id', 'Name', 'Created at', ];
	$x->ColFieldName = ['id', 'owner_id', 'name', 'created_at', ];
	$x->ColNumber  = [1, 2, 3, 4, ];

	// template paths below are based on the app main directory
	$x->Template = 'templates/circles_templateTV.html';
	$x->SelectedTemplate = 'templates/circles_templateTVS.html';
	$x->TemplateDV = 'templates/circles_templateDV.html';
	$x->TemplateDVP = 'templates/circles_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HasCalculatedFields = false;
	$x->AllowConsoleLog = false;
	$x->AllowDVNavigation = true;

	// hook: circles_init
	$render = true;
	if(function_exists('circles_init')) {
		$args = [];
		$render = circles_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: circles_header
	$headerCode = '';
	if(function_exists('circles_header')) {
		$args = [];
		$headerCode = circles_header($x->ContentType, getMemberInfo(), $args);
	}

	if(!$headerCode) {
		include_once(__DIR__ . '/header.php');
	} else {
		ob_start();
		include_once(__DIR__ . '/header.php');
		echo str_replace('<%%HEADER%%>', ob_get_clean(), $headerCode);
	}

	echo $x->HTML;

	// hook: circles_footer
	$footerCode = '';
	if(function_exists('circles_footer')) {
		$args = [];
		$footerCode = circles_footer($x->ContentType, getMemberInfo(), $args);
	}

	if(!$footerCode) {
		include_once(__DIR__ . '/footer.php');
	} else {
		ob_start();
		include_once(__DIR__ . '/footer.php');
		echo str_replace('<%%FOOTER%%>', ob_get_clean(), $footerCode);
	}
