<?php
// This script and data application was generated by AppGini, https://bigprof.com/appgini
// Download AppGini for free from https://bigprof.com/appgini/download/

	include_once(__DIR__ . '/lib.php');
	@include_once(__DIR__ . '/hooks/circle_members.php');
	include_once(__DIR__ . '/circle_members_dml.php');

	// mm: can the current member access this page?
	$perm = getTablePermissions('circle_members');
	if(!$perm['access']) {
		echo error_message($Translation['tableAccessDenied']);
		exit;
	}

	$x = new DataList;
	$x->TableName = 'circle_members';

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = [
		"`circle_members`.`id`" => "id",
		"`circle_members`.`circle_id`" => "circle_id",
		"`circle_members`.`user_id`" => "user_id",
		"`circle_members`.`added_at`" => "added_at",
	];
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = [
		1 => '`circle_members`.`id`',
		2 => '`circle_members`.`circle_id`',
		3 => '`circle_members`.`user_id`',
		4 => '`circle_members`.`added_at`',
	];

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = [
		"`circle_members`.`id`" => "id",
		"`circle_members`.`circle_id`" => "circle_id",
		"`circle_members`.`user_id`" => "user_id",
		"`circle_members`.`added_at`" => "added_at",
	];
	// Fields that can be filtered
	$x->QueryFieldsFilters = [
		"`circle_members`.`id`" => "Id",
		"`circle_members`.`circle_id`" => "Circle id",
		"`circle_members`.`user_id`" => "User id",
		"`circle_members`.`added_at`" => "Added at",
	];

	// Fields that can be quick searched
	$x->QueryFieldsQS = [
		"`circle_members`.`id`" => "id",
		"`circle_members`.`circle_id`" => "circle_id",
		"`circle_members`.`user_id`" => "user_id",
		"`circle_members`.`added_at`" => "added_at",
	];

	// Lookup fields that can be used as filterers
	$x->filterers = [];

	$x->QueryFrom = "`circle_members` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm['view'] == 0 ? 1 : 0);
	$x->AllowDelete = $perm['delete'];
	$x->AllowMassDelete = (getLoggedAdmin() !== false);
	$x->AllowInsert = $perm['insert'];
	$x->AllowUpdate = $perm['edit'];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = (getLoggedAdmin() !== false);
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = 1;
	$x->AllowAdminShowSQL = showSQL();
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation['quick search'];
	$x->ScriptFileName = 'circle_members_view.php';
	$x->TableTitle = 'Circle members';
	$x->TableIcon = 'table.gif';
	$x->PrimaryKey = '`circle_members`.`id`';

	$x->ColWidth = [150, 150, 150, 150, ];
	$x->ColCaption = ['Id', 'Circle id', 'User id', 'Added at', ];
	$x->ColFieldName = ['id', 'circle_id', 'user_id', 'added_at', ];
	$x->ColNumber  = [1, 2, 3, 4, ];

	// template paths below are based on the app main directory
	$x->Template = 'templates/circle_members_templateTV.html';
	$x->SelectedTemplate = 'templates/circle_members_templateTVS.html';
	$x->TemplateDV = 'templates/circle_members_templateDV.html';
	$x->TemplateDVP = 'templates/circle_members_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HasCalculatedFields = false;
	$x->AllowConsoleLog = false;
	$x->AllowDVNavigation = true;

	// hook: circle_members_init
	$render = true;
	if(function_exists('circle_members_init')) {
		$args = [];
		$render = circle_members_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: circle_members_header
	$headerCode = '';
	if(function_exists('circle_members_header')) {
		$args = [];
		$headerCode = circle_members_header($x->ContentType, getMemberInfo(), $args);
	}

	if(!$headerCode) {
		include_once(__DIR__ . '/header.php');
	} else {
		ob_start();
		include_once(__DIR__ . '/header.php');
		echo str_replace('<%%HEADER%%>', ob_get_clean(), $headerCode);
	}

	echo $x->HTML;

	// hook: circle_members_footer
	$footerCode = '';
	if(function_exists('circle_members_footer')) {
		$args = [];
		$footerCode = circle_members_footer($x->ContentType, getMemberInfo(), $args);
	}

	if(!$footerCode) {
		include_once(__DIR__ . '/footer.php');
	} else {
		ob_start();
		include_once(__DIR__ . '/footer.php');
		echo str_replace('<%%FOOTER%%>', ob_get_clean(), $footerCode);
	}
