<?php
// This script and data application was generated by AppGini, https://bigprof.com/appgini
// Download AppGini for free from https://bigprof.com/appgini/download/

	include_once(__DIR__ . '/lib.php');
	@include_once(__DIR__ . '/hooks/followers.php');
	include_once(__DIR__ . '/followers_dml.php');

	// mm: can the current member access this page?
	$perm = getTablePermissions('followers');
	if(!$perm['access']) {
		echo error_message($Translation['tableAccessDenied']);
		exit;
	}

	$x = new DataList;
	$x->TableName = 'followers';

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = [
		"`followers`.`id`" => "id",
		"`followers`.`follower_id`" => "follower_id",
		"`followers`.`following_id`" => "following_id",
		"`followers`.`created_at`" => "created_at",
	];
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = [
		1 => '`followers`.`id`',
		2 => '`followers`.`follower_id`',
		3 => '`followers`.`following_id`',
		4 => '`followers`.`created_at`',
	];

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = [
		"`followers`.`id`" => "id",
		"`followers`.`follower_id`" => "follower_id",
		"`followers`.`following_id`" => "following_id",
		"`followers`.`created_at`" => "created_at",
	];
	// Fields that can be filtered
	$x->QueryFieldsFilters = [
		"`followers`.`id`" => "Id",
		"`followers`.`follower_id`" => "Follower id",
		"`followers`.`following_id`" => "Following id",
		"`followers`.`created_at`" => "Created at",
	];

	// Fields that can be quick searched
	$x->QueryFieldsQS = [
		"`followers`.`id`" => "id",
		"`followers`.`follower_id`" => "follower_id",
		"`followers`.`following_id`" => "following_id",
		"`followers`.`created_at`" => "created_at",
	];

	// Lookup fields that can be used as filterers
	$x->filterers = [];

	$x->QueryFrom = "`followers` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm['view'] == 0 ? 1 : 0);
	$x->AllowDelete = $perm['delete'];
	$x->AllowMassDelete = (getLoggedAdmin() !== false);
	$x->AllowInsert = $perm['insert'];
	$x->AllowUpdate = $perm['edit'];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = (getLoggedAdmin() !== false);
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = 1;
	$x->AllowAdminShowSQL = showSQL();
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation['quick search'];
	$x->ScriptFileName = 'followers_view.php';
	$x->TableTitle = 'Followers';
	$x->TableIcon = 'table.gif';
	$x->PrimaryKey = '`followers`.`id`';

	$x->ColWidth = [150, 150, 150, 150, ];
	$x->ColCaption = ['Id', 'Follower id', 'Following id', 'Created at', ];
	$x->ColFieldName = ['id', 'follower_id', 'following_id', 'created_at', ];
	$x->ColNumber  = [1, 2, 3, 4, ];

	// template paths below are based on the app main directory
	$x->Template = 'templates/followers_templateTV.html';
	$x->SelectedTemplate = 'templates/followers_templateTVS.html';
	$x->TemplateDV = 'templates/followers_templateDV.html';
	$x->TemplateDVP = 'templates/followers_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HasCalculatedFields = false;
	$x->AllowConsoleLog = false;
	$x->AllowDVNavigation = true;

	// hook: followers_init
	$render = true;
	if(function_exists('followers_init')) {
		$args = [];
		$render = followers_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: followers_header
	$headerCode = '';
	if(function_exists('followers_header')) {
		$args = [];
		$headerCode = followers_header($x->ContentType, getMemberInfo(), $args);
	}

	if(!$headerCode) {
		include_once(__DIR__ . '/header.php');
	} else {
		ob_start();
		include_once(__DIR__ . '/header.php');
		echo str_replace('<%%HEADER%%>', ob_get_clean(), $headerCode);
	}

	echo $x->HTML;

	// hook: followers_footer
	$footerCode = '';
	if(function_exists('followers_footer')) {
		$args = [];
		$footerCode = followers_footer($x->ContentType, getMemberInfo(), $args);
	}

	if(!$footerCode) {
		include_once(__DIR__ . '/footer.php');
	} else {
		ob_start();
		include_once(__DIR__ . '/footer.php');
		echo str_replace('<%%FOOTER%%>', ob_get_clean(), $footerCode);
	}
