<?php
// This script and data application was generated by AppGini, https://bigprof.com/appgini
// Download AppGini for free from https://bigprof.com/appgini/download/

	include_once(__DIR__ . '/lib.php');
	@include_once(__DIR__ . '/hooks/friends.php');
	include_once(__DIR__ . '/friends_dml.php');

	// mm: can the current member access this page?
	$perm = getTablePermissions('friends');
	if(!$perm['access']) {
		echo error_message($Translation['tableAccessDenied']);
		exit;
	}

	$x = new DataList;
	$x->TableName = 'friends';

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = [
		"`friends`.`id`" => "id",
		"`friends`.`user1_id`" => "user1_id",
		"`friends`.`user2_id`" => "user2_id",
		"`friends`.`created_at`" => "created_at",
	];
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = [
		1 => '`friends`.`id`',
		2 => '`friends`.`user1_id`',
		3 => '`friends`.`user2_id`',
		4 => '`friends`.`created_at`',
	];

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = [
		"`friends`.`id`" => "id",
		"`friends`.`user1_id`" => "user1_id",
		"`friends`.`user2_id`" => "user2_id",
		"`friends`.`created_at`" => "created_at",
	];
	// Fields that can be filtered
	$x->QueryFieldsFilters = [
		"`friends`.`id`" => "Id",
		"`friends`.`user1_id`" => "User1 id",
		"`friends`.`user2_id`" => "User2 id",
		"`friends`.`created_at`" => "Created at",
	];

	// Fields that can be quick searched
	$x->QueryFieldsQS = [
		"`friends`.`id`" => "id",
		"`friends`.`user1_id`" => "user1_id",
		"`friends`.`user2_id`" => "user2_id",
		"`friends`.`created_at`" => "created_at",
	];

	// Lookup fields that can be used as filterers
	$x->filterers = [];

	$x->QueryFrom = "`friends` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm['view'] == 0 ? 1 : 0);
	$x->AllowDelete = $perm['delete'];
	$x->AllowMassDelete = (getLoggedAdmin() !== false);
	$x->AllowInsert = $perm['insert'];
	$x->AllowUpdate = $perm['edit'];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = (getLoggedAdmin() !== false);
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = 1;
	$x->AllowAdminShowSQL = showSQL();
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation['quick search'];
	$x->ScriptFileName = 'friends_view.php';
	$x->TableTitle = 'Friends';
	$x->TableIcon = 'table.gif';
	$x->PrimaryKey = '`friends`.`id`';

	$x->ColWidth = [150, 150, 150, 150, ];
	$x->ColCaption = ['Id', 'User1 id', 'User2 id', 'Created at', ];
	$x->ColFieldName = ['id', 'user1_id', 'user2_id', 'created_at', ];
	$x->ColNumber  = [1, 2, 3, 4, ];

	// template paths below are based on the app main directory
	$x->Template = 'templates/friends_templateTV.html';
	$x->SelectedTemplate = 'templates/friends_templateTVS.html';
	$x->TemplateDV = 'templates/friends_templateDV.html';
	$x->TemplateDVP = 'templates/friends_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HasCalculatedFields = false;
	$x->AllowConsoleLog = false;
	$x->AllowDVNavigation = true;

	// hook: friends_init
	$render = true;
	if(function_exists('friends_init')) {
		$args = [];
		$render = friends_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: friends_header
	$headerCode = '';
	if(function_exists('friends_header')) {
		$args = [];
		$headerCode = friends_header($x->ContentType, getMemberInfo(), $args);
	}

	if(!$headerCode) {
		include_once(__DIR__ . '/header.php');
	} else {
		ob_start();
		include_once(__DIR__ . '/header.php');
		echo str_replace('<%%HEADER%%>', ob_get_clean(), $headerCode);
	}

	echo $x->HTML;

	// hook: friends_footer
	$footerCode = '';
	if(function_exists('friends_footer')) {
		$args = [];
		$footerCode = friends_footer($x->ContentType, getMemberInfo(), $args);
	}

	if(!$footerCode) {
		include_once(__DIR__ . '/footer.php');
	} else {
		ob_start();
		include_once(__DIR__ . '/footer.php');
		echo str_replace('<%%FOOTER%%>', ob_get_clean(), $footerCode);
	}
