<?php
// This script and data application was generated by AppGini, https://bigprof.com/appgini
// Download AppGini for free from https://bigprof.com/appgini/download/

	include_once(__DIR__ . '/lib.php');
	@include_once(__DIR__ . '/hooks/messages.php');
	include_once(__DIR__ . '/messages_dml.php');

	// mm: can the current member access this page?
	$perm = getTablePermissions('messages');
	if(!$perm['access']) {
		echo error_message($Translation['tableAccessDenied']);
		exit;
	}

	$x = new DataList;
	$x->TableName = 'messages';

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = [
		"`messages`.`id`" => "id",
		"`messages`.`sender_id`" => "sender_id",
		"`messages`.`receiver_id`" => "receiver_id",
		"`messages`.`body`" => "body",
		"`messages`.`created_at`" => "created_at",
	];
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = [
		1 => '`messages`.`id`',
		2 => '`messages`.`sender_id`',
		3 => '`messages`.`receiver_id`',
		4 => 4,
		5 => '`messages`.`created_at`',
	];

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = [
		"`messages`.`id`" => "id",
		"`messages`.`sender_id`" => "sender_id",
		"`messages`.`receiver_id`" => "receiver_id",
		"`messages`.`body`" => "body",
		"`messages`.`created_at`" => "created_at",
	];
	// Fields that can be filtered
	$x->QueryFieldsFilters = [
		"`messages`.`id`" => "Id",
		"`messages`.`sender_id`" => "Sender id",
		"`messages`.`receiver_id`" => "Receiver id",
		"`messages`.`body`" => "Body",
		"`messages`.`created_at`" => "Created at",
	];

	// Fields that can be quick searched
	$x->QueryFieldsQS = [
		"`messages`.`id`" => "id",
		"`messages`.`sender_id`" => "sender_id",
		"`messages`.`receiver_id`" => "receiver_id",
		"`messages`.`body`" => "body",
		"`messages`.`created_at`" => "created_at",
	];

	// Lookup fields that can be used as filterers
	$x->filterers = [];

	$x->QueryFrom = "`messages` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm['view'] == 0 ? 1 : 0);
	$x->AllowDelete = $perm['delete'];
	$x->AllowMassDelete = (getLoggedAdmin() !== false);
	$x->AllowInsert = $perm['insert'];
	$x->AllowUpdate = $perm['edit'];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = (getLoggedAdmin() !== false);
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = 1;
	$x->AllowAdminShowSQL = showSQL();
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation['quick search'];
	$x->ScriptFileName = 'messages_view.php';
	$x->TableTitle = 'Messages';
	$x->TableIcon = 'table.gif';
	$x->PrimaryKey = '`messages`.`id`';

	$x->ColWidth = [150, 150, 150, 150, 150, ];
	$x->ColCaption = ['Id', 'Sender id', 'Receiver id', 'Body', 'Created at', ];
	$x->ColFieldName = ['id', 'sender_id', 'receiver_id', 'body', 'created_at', ];
	$x->ColNumber  = [1, 2, 3, 4, 5, ];

	// template paths below are based on the app main directory
	$x->Template = 'templates/messages_templateTV.html';
	$x->SelectedTemplate = 'templates/messages_templateTVS.html';
	$x->TemplateDV = 'templates/messages_templateDV.html';
	$x->TemplateDVP = 'templates/messages_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HasCalculatedFields = false;
	$x->AllowConsoleLog = false;
	$x->AllowDVNavigation = true;

	// hook: messages_init
	$render = true;
	if(function_exists('messages_init')) {
		$args = [];
		$render = messages_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: messages_header
	$headerCode = '';
	if(function_exists('messages_header')) {
		$args = [];
		$headerCode = messages_header($x->ContentType, getMemberInfo(), $args);
	}

	if(!$headerCode) {
		include_once(__DIR__ . '/header.php');
	} else {
		ob_start();
		include_once(__DIR__ . '/header.php');
		echo str_replace('<%%HEADER%%>', ob_get_clean(), $headerCode);
	}

	echo $x->HTML;

	// hook: messages_footer
	$footerCode = '';
	if(function_exists('messages_footer')) {
		$args = [];
		$footerCode = messages_footer($x->ContentType, getMemberInfo(), $args);
	}

	if(!$footerCode) {
		include_once(__DIR__ . '/footer.php');
	} else {
		ob_start();
		include_once(__DIR__ . '/footer.php');
		echo str_replace('<%%FOOTER%%>', ob_get_clean(), $footerCode);
	}
