<?php
// This script and data application was generated by AppGini, https://bigprof.com/appgini
// Download AppGini for free from https://bigprof.com/appgini/download/

	include_once(__DIR__ . '/lib.php');
	@include_once(__DIR__ . '/hooks/password_resets.php');
	include_once(__DIR__ . '/password_resets_dml.php');

	// mm: can the current member access this page?
	$perm = getTablePermissions('password_resets');
	if(!$perm['access']) {
		echo error_message($Translation['tableAccessDenied']);
		exit;
	}

	$x = new DataList;
	$x->TableName = 'password_resets';

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = [
		"`password_resets`.`id`" => "id",
		"`password_resets`.`user_id`" => "user_id",
		"`password_resets`.`new_password_hash`" => "new_password_hash",
		"`password_resets`.`requested_at`" => "requested_at",
	];
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = [
		1 => '`password_resets`.`id`',
		2 => '`password_resets`.`user_id`',
		3 => 3,
		4 => '`password_resets`.`requested_at`',
	];

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = [
		"`password_resets`.`id`" => "id",
		"`password_resets`.`user_id`" => "user_id",
		"`password_resets`.`new_password_hash`" => "new_password_hash",
		"`password_resets`.`requested_at`" => "requested_at",
	];
	// Fields that can be filtered
	$x->QueryFieldsFilters = [
		"`password_resets`.`id`" => "Id",
		"`password_resets`.`user_id`" => "User id",
		"`password_resets`.`new_password_hash`" => "New password hash",
		"`password_resets`.`requested_at`" => "Requested at",
	];

	// Fields that can be quick searched
	$x->QueryFieldsQS = [
		"`password_resets`.`id`" => "id",
		"`password_resets`.`user_id`" => "user_id",
		"`password_resets`.`new_password_hash`" => "new_password_hash",
		"`password_resets`.`requested_at`" => "requested_at",
	];

	// Lookup fields that can be used as filterers
	$x->filterers = [];

	$x->QueryFrom = "`password_resets` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm['view'] == 0 ? 1 : 0);
	$x->AllowDelete = $perm['delete'];
	$x->AllowMassDelete = (getLoggedAdmin() !== false);
	$x->AllowInsert = $perm['insert'];
	$x->AllowUpdate = $perm['edit'];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = (getLoggedAdmin() !== false);
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = 1;
	$x->AllowAdminShowSQL = showSQL();
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation['quick search'];
	$x->ScriptFileName = 'password_resets_view.php';
	$x->TableTitle = 'Password resets';
	$x->TableIcon = 'table.gif';
	$x->PrimaryKey = '`password_resets`.`id`';

	$x->ColWidth = [150, 150, 150, 150, ];
	$x->ColCaption = ['Id', 'User id', 'New password hash', 'Requested at', ];
	$x->ColFieldName = ['id', 'user_id', 'new_password_hash', 'requested_at', ];
	$x->ColNumber  = [1, 2, 3, 4, ];

	// template paths below are based on the app main directory
	$x->Template = 'templates/password_resets_templateTV.html';
	$x->SelectedTemplate = 'templates/password_resets_templateTVS.html';
	$x->TemplateDV = 'templates/password_resets_templateDV.html';
	$x->TemplateDVP = 'templates/password_resets_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HasCalculatedFields = false;
	$x->AllowConsoleLog = false;
	$x->AllowDVNavigation = true;

	// hook: password_resets_init
	$render = true;
	if(function_exists('password_resets_init')) {
		$args = [];
		$render = password_resets_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: password_resets_header
	$headerCode = '';
	if(function_exists('password_resets_header')) {
		$args = [];
		$headerCode = password_resets_header($x->ContentType, getMemberInfo(), $args);
	}

	if(!$headerCode) {
		include_once(__DIR__ . '/header.php');
	} else {
		ob_start();
		include_once(__DIR__ . '/header.php');
		echo str_replace('<%%HEADER%%>', ob_get_clean(), $headerCode);
	}

	echo $x->HTML;

	// hook: password_resets_footer
	$footerCode = '';
	if(function_exists('password_resets_footer')) {
		$args = [];
		$footerCode = password_resets_footer($x->ContentType, getMemberInfo(), $args);
	}

	if(!$footerCode) {
		include_once(__DIR__ . '/footer.php');
	} else {
		ob_start();
		include_once(__DIR__ . '/footer.php');
		echo str_replace('<%%FOOTER%%>', ob_get_clean(), $footerCode);
	}
