<?php
// This script and data application was generated by AppGini, https://bigprof.com/appgini
// Download AppGini for free from https://bigprof.com/appgini/download/

	include_once(__DIR__ . '/lib.php');
	@include_once(__DIR__ . '/hooks/posts.php');
	include_once(__DIR__ . '/posts_dml.php');

	// mm: can the current member access this page?
	$perm = getTablePermissions('posts');
	if(!$perm['access']) {
		echo error_message($Translation['tableAccessDenied']);
		exit;
	}

	$x = new DataList;
	$x->TableName = 'posts';

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = [
		"`posts`.`id`" => "id",
		"`posts`.`author_id`" => "author_id",
		"`posts`.`content`" => "content",
		"`posts`.`circle_id`" => "circle_id",
		"`posts`.`created_at`" => "created_at",
		"`posts`.`visibility`" => "visibility",
	];
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = [
		1 => '`posts`.`id`',
		2 => '`posts`.`author_id`',
		3 => 3,
		4 => '`posts`.`circle_id`',
		5 => '`posts`.`created_at`',
		6 => 6,
	];

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = [
		"`posts`.`id`" => "id",
		"`posts`.`author_id`" => "author_id",
		"`posts`.`content`" => "content",
		"`posts`.`circle_id`" => "circle_id",
		"`posts`.`created_at`" => "created_at",
		"`posts`.`visibility`" => "visibility",
	];
	// Fields that can be filtered
	$x->QueryFieldsFilters = [
		"`posts`.`id`" => "Id",
		"`posts`.`author_id`" => "Author id",
		"`posts`.`content`" => "Content",
		"`posts`.`circle_id`" => "Circle id",
		"`posts`.`created_at`" => "Created at",
		"`posts`.`visibility`" => "Visibility",
	];

	// Fields that can be quick searched
	$x->QueryFieldsQS = [
		"`posts`.`id`" => "id",
		"`posts`.`author_id`" => "author_id",
		"`posts`.`content`" => "content",
		"`posts`.`circle_id`" => "circle_id",
		"`posts`.`created_at`" => "created_at",
		"`posts`.`visibility`" => "visibility",
	];

	// Lookup fields that can be used as filterers
	$x->filterers = [];

	$x->QueryFrom = "`posts` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm['view'] == 0 ? 1 : 0);
	$x->AllowDelete = $perm['delete'];
	$x->AllowMassDelete = (getLoggedAdmin() !== false);
	$x->AllowInsert = $perm['insert'];
	$x->AllowUpdate = $perm['edit'];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = (getLoggedAdmin() !== false);
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = 1;
	$x->AllowAdminShowSQL = showSQL();
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation['quick search'];
	$x->ScriptFileName = 'posts_view.php';
	$x->TableTitle = 'Posts';
	$x->TableIcon = 'table.gif';
	$x->PrimaryKey = '`posts`.`id`';

	$x->ColWidth = [150, 150, 150, 150, 150, 150, ];
	$x->ColCaption = ['Id', 'Author id', 'Content', 'Circle id', 'Created at', 'Visibility', ];
	$x->ColFieldName = ['id', 'author_id', 'content', 'circle_id', 'created_at', 'visibility', ];
	$x->ColNumber  = [1, 2, 3, 4, 5, 6, ];

	// template paths below are based on the app main directory
	$x->Template = 'templates/posts_templateTV.html';
	$x->SelectedTemplate = 'templates/posts_templateTVS.html';
	$x->TemplateDV = 'templates/posts_templateDV.html';
	$x->TemplateDVP = 'templates/posts_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HasCalculatedFields = false;
	$x->AllowConsoleLog = false;
	$x->AllowDVNavigation = true;

	// hook: posts_init
	$render = true;
	if(function_exists('posts_init')) {
		$args = [];
		$render = posts_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: posts_header
	$headerCode = '';
	if(function_exists('posts_header')) {
		$args = [];
		$headerCode = posts_header($x->ContentType, getMemberInfo(), $args);
	}

	if(!$headerCode) {
		include_once(__DIR__ . '/header.php');
	} else {
		ob_start();
		include_once(__DIR__ . '/header.php');
		echo str_replace('<%%HEADER%%>', ob_get_clean(), $headerCode);
	}

	echo $x->HTML;

	// hook: posts_footer
	$footerCode = '';
	if(function_exists('posts_footer')) {
		$args = [];
		$footerCode = posts_footer($x->ContentType, getMemberInfo(), $args);
	}

	if(!$footerCode) {
		include_once(__DIR__ . '/footer.php');
	} else {
		ob_start();
		include_once(__DIR__ . '/footer.php');
		echo str_replace('<%%FOOTER%%>', ob_get_clean(), $footerCode);
	}
