<?php
// This script and data application was generated by AppGini, https://bigprof.com/appgini
// Download AppGini for free from https://bigprof.com/appgini/download/

	include_once(__DIR__ . '/lib.php');
	@include_once(__DIR__ . '/hooks/post_saves.php');
	include_once(__DIR__ . '/post_saves_dml.php');

	// mm: can the current member access this page?
	$perm = getTablePermissions('post_saves');
	if(!$perm['access']) {
		echo error_message($Translation['tableAccessDenied']);
		exit;
	}

	$x = new DataList;
	$x->TableName = 'post_saves';

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = [
		"`post_saves`.`id`" => "id",
		"`post_saves`.`user_id`" => "user_id",
		"`post_saves`.`post_id`" => "post_id",
		"`post_saves`.`created_at`" => "created_at",
	];
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = [
		1 => '`post_saves`.`id`',
		2 => '`post_saves`.`user_id`',
		3 => '`post_saves`.`post_id`',
		4 => '`post_saves`.`created_at`',
	];

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = [
		"`post_saves`.`id`" => "id",
		"`post_saves`.`user_id`" => "user_id",
		"`post_saves`.`post_id`" => "post_id",
		"`post_saves`.`created_at`" => "created_at",
	];
	// Fields that can be filtered
	$x->QueryFieldsFilters = [
		"`post_saves`.`id`" => "Id",
		"`post_saves`.`user_id`" => "User id",
		"`post_saves`.`post_id`" => "Post id",
		"`post_saves`.`created_at`" => "Created at",
	];

	// Fields that can be quick searched
	$x->QueryFieldsQS = [
		"`post_saves`.`id`" => "id",
		"`post_saves`.`user_id`" => "user_id",
		"`post_saves`.`post_id`" => "post_id",
		"`post_saves`.`created_at`" => "created_at",
	];

	// Lookup fields that can be used as filterers
	$x->filterers = [];

	$x->QueryFrom = "`post_saves` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm['view'] == 0 ? 1 : 0);
	$x->AllowDelete = $perm['delete'];
	$x->AllowMassDelete = (getLoggedAdmin() !== false);
	$x->AllowInsert = $perm['insert'];
	$x->AllowUpdate = $perm['edit'];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = (getLoggedAdmin() !== false);
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = 1;
	$x->AllowAdminShowSQL = showSQL();
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation['quick search'];
	$x->ScriptFileName = 'post_saves_view.php';
	$x->TableTitle = 'Post saves';
	$x->TableIcon = 'table.gif';
	$x->PrimaryKey = '`post_saves`.`id`';

	$x->ColWidth = [150, 150, 150, 150, ];
	$x->ColCaption = ['Id', 'User id', 'Post id', 'Created at', ];
	$x->ColFieldName = ['id', 'user_id', 'post_id', 'created_at', ];
	$x->ColNumber  = [1, 2, 3, 4, ];

	// template paths below are based on the app main directory
	$x->Template = 'templates/post_saves_templateTV.html';
	$x->SelectedTemplate = 'templates/post_saves_templateTVS.html';
	$x->TemplateDV = 'templates/post_saves_templateDV.html';
	$x->TemplateDVP = 'templates/post_saves_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HasCalculatedFields = false;
	$x->AllowConsoleLog = false;
	$x->AllowDVNavigation = true;

	// hook: post_saves_init
	$render = true;
	if(function_exists('post_saves_init')) {
		$args = [];
		$render = post_saves_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: post_saves_header
	$headerCode = '';
	if(function_exists('post_saves_header')) {
		$args = [];
		$headerCode = post_saves_header($x->ContentType, getMemberInfo(), $args);
	}

	if(!$headerCode) {
		include_once(__DIR__ . '/header.php');
	} else {
		ob_start();
		include_once(__DIR__ . '/header.php');
		echo str_replace('<%%HEADER%%>', ob_get_clean(), $headerCode);
	}

	echo $x->HTML;

	// hook: post_saves_footer
	$footerCode = '';
	if(function_exists('post_saves_footer')) {
		$args = [];
		$footerCode = post_saves_footer($x->ContentType, getMemberInfo(), $args);
	}

	if(!$footerCode) {
		include_once(__DIR__ . '/footer.php');
	} else {
		ob_start();
		include_once(__DIR__ . '/footer.php');
		echo str_replace('<%%FOOTER%%>', ob_get_clean(), $footerCode);
	}
